name: FlarePlugin
version: $1.0
main: org.markmanflame55.flareplugin.FlarePlugin
api-version: 1.20
commands:
  menu:
    description: Get the Operator Block Item (ONLY WITH OP)
    usage: <command> [<target>]
  credits:
    description: Credits of the plugin
  viewrecipe:
    description: View Recipes
    usage: <command> <recipe_id>
  funny:
    description: funny
  flarespawn:
    description: Spawn custom entities from Flare Plugin
    usage: <command> <mob_id>
  flaregive:
    description: Give a FlareItem to a player
    usage: <command> <player> <item_id>
